# Editor: Maheen Raza
version: "3.7"
services:
  managedhost-app-1:
    build: 
      context: managed-host/alpine/app1
    restart: unless-stopped
    network_mode: "bridge"
    environment:
      - SSH_ENABLE_ROOT=true
    volumes:
      - ./secrets/id_rsa_container.pub:/root/.ssh/authorized_keys # mounting the public key from the host to the container
    ports: # mapping container port to host ports for Web and SSH
      - "3000:3000"
      - "2223:2223"
      
  managedhost-app-2:
    build: 
      context: managed-host/alpine/app2
    restart: unless-stopped
    network_mode: "bridge"
    environment:
      - SSH_ENABLE_ROOT=true
    volumes:
      - ./secrets/id_rsa_container.pub:/root/.ssh/authorized_keys # mounting the public key from the host to the container
    ports: # mapping container port to host ports for Web and SSH
      - "3001:3000"
      - "2224:2224"
  
  managedhost-app-3:
    build: 
      context: managed-host/alpine/app3
    restart: unless-stopped
    network_mode: "bridge"
    environment:
      - SSH_ENABLE_ROOT=true
    volumes:
      - ./secrets/id_rsa_container.pub:/root/.ssh/authorized_keys # mounting the public key from the host to the container
    ports: # mapping container port to host ports for Web and SSH
      - "3002:3000"
      - "2225:2225"

  loadbalancer: # defining our nginx load balancer service
    image: nginx:latest # will pull the latest version of the nginx image
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro # mounting our volumes to the container
    ports:
      - "80:80" # mapping host port 80 to container port 80
