# Inventory file
ungrouped:
app_group: 
  hosts: # defining the three different groups to manage
    managedhost-app-1:
      ansible_host: 0.0.0.0
      ansible_connection: ssh
      ansible_port: 2223  # port used in the docker compose file for managedhost-app-1
      ansible_user: root
    managedhost-app-2:
      ansible_host: 0.0.0.0
      ansible_connection: ssh
      ansible_port: 2224  # port defined in the docker compose file for managedhost-app-2
      ansible_user: root
    managedhost-app-3:
      ansible_host: 0.0.0.0
      ansible_connection: ssh
      ansible_port: 2225  # port defined in the docker compose file in managedhost-app-3
      ansible_user: root
      
loadbalancer:
  hosts:
    localhost:
      ansible_connection: local
